version: '3.9'

services:
  database:
    container_name: example-database
    image: mysql:8.0.33
    restart: "always"
    volumes:
      - data:/var/lib/mysql
      - ./classicmodels.sql:/docker-entrypoint-initdb.d/00_init.sql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 9ijn8uhb
      MYSQL_DATABASE: example
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      TZ: UTC
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  backup:
    container_name: example-backup
    image: tiredofit/db-backup:3.9.6
    restart: "always"
    volumes:
      - backup:/backup
    environment:
      TZ: UTC
      TIMEZONE: Etc/UTC
      DB_TYPE: mysql
      DB_HOST: database
      DB_NAME: example
      DB_USER: admin
      DB_PASS: 9ijn8uhb
      DB_DUMP_BEGIN: "+0"
      DB_DUMP_FREQ: "1440"
      DB_CLEANUP_TIME: "10080"
      SPLIT_DB: FALSE
      CHECKSUM: SHA1
      COMPRESSION: GZ
      CONTAINER_ENABLE_MONITORING: FALSE
      DEBUG_MODE: FALSE
    links:
      - database
    depends_on:
      database:
        condition: service_healthy

volumes:
  data:
    name: example-data
  backup:
    name: example-data-backup

networks:
  default:
    name: example-network
